name: Metrics
on:
  # Schedule updates (every 24 hours)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run it manually
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: CHYou2Sef
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Tunis
          
          # ğŸ¨ THEME: Cosmos/Dark
          config_style: dark
          
          # ğŸ“Š THE ACTIVITY GRAPH (The one you circled!)
          plugin_followup: yes
          plugin_followup_sections: repositories
          
          # ğŸ† (Optional) Display achievements in the image too
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: C
